name: Deploy to Synology NAS

on:
  push:
    branches:
      - master
    paths:
      - 'docker-compose.yml'
      - 'app.py'
      - 'updream_crawler.py'
      - '.github/workflows/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to NAS via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          key: ${{ secrets.NAS_SSH_KEY }}
          script: |
            cd /volume1/git_storage/omsprj
            git pull

            # 파일별 조건 분기
            if git diff --name-only HEAD~1 HEAD | grep -q "docker-compose.yml"; then
              echo "docker-compose.yml 변경 감지 → 전체 빌드"
              /usr/local/bin/docker-compose up -d --build
            elif git diff --name-only HEAD~1 HEAD | grep -E "app.py|updream_crawler.py" >/dev/null; then
              echo "app.py 또는 updream_crawler.py 변경_
